name: Create URL Link for Static HTML Page

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create_link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Build HTML
        run: |
          # Replace this command with your build command
          echo "<html><body><h1>Hello, world!</h1></body></html>" > index.html
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./index.html
          publish_branch: gh-pages
