name: Create URL Link for Static HTML Page

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  create_link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Build HTML
        run: |
          # Replace this command with your build command
          mkdir -p ${{ github.workspace }}/dist
          echo "<html><body><h1>Hello, world!</h1></body></html>" > mkdir -p ${{ github.workspace }}/dist/index.html
      - name: Clone other repository
        uses: actions/checkout@v2
        with:
          repository: pemsher/pemsher.github.io
          token: ${{ secrets.GH_ACTION_TOKEN }}
          ref: master

      - name: Copy static content
        run: |
          # Replace this command with your command to copy static content
          cp -r ${{ github.workspace }}/dist/* .

      - name: Push changes
        run: |
          git config --global user.email "<email>"
          git config --global user.name "<username>"
          git add .
          git commit -m "Push static content from PR #${{ github.event.pull_request.number }}"
          git push
